// Generated by the WOLips Templateengine Plug-in at Aug 15, 2009 8:38:23 PM
package womovies;

import com.webobjects.appserver.WOApplication;
import com.webobjects.foundation.NSBundle;
import com.webobjects.foundation.NSLog;

public class Application extends WOApplication {

    public static void main(String argv[]) {
        WOApplication.main(argv, Application.class);
    }

    public Application() {
        super();
        NSLog.out.appendln("Welcome to " + this.name() + " !");
        
        /* ** put your initialization code in here ** */
        NSBundle bundle = NSBundle.mainBundle();
        String file = bundle.bundlePath() + "/Contents/Resources/Movies";
        System.setProperty("Movies.URL", "jdbc:h2:file:" + file);
    }
}